function S=getArea(triangle)
% triangle is a 3x2 matrix
S=0.5*( (triangle(2,1)-triangle(1,1))* ...
        (triangle(3,2)-triangle(1,2))- ...
        (triangle(2,2)-triangle(1,2))* ...
        (triangle(3,1)-triangle(1,1)) );
end